### ISSUE TITLE
提一个bug，两块屏幕，偶尔会出现

### ISSUE THREAD

**Issue by six7ths** [thqby/wincapture#1]
因为，我有两块屏幕，截屏时，需要交替截屏

所以，我这是一个wgc0和wgc1，wgc0截取第一屏幕，wgc1截取副屏

大部分时间运行良好；结果总有极少数时间，会wcg0截屏到了副屏，导致下一步ocr失败，产生异常

请问，这可能是什么原因，有什么办法规避呢？ 我没找到wincaputure的log，我自己通过wincapture 截取去的bimpbuffer save图像，发现的这个问题

补充一点，我vscode在副屏，启动时wgc时，从副屏的vscode中启动的，但出问题这次识别，不是wgc0第一次被调用，时第二次被调用时，没截取主屏，反而截取了一块副屏，很是奇怪

**Comment by thqby** [comment]
不知道，有空再看
